### ISSUE TITLE
Support Sqlalchemy 1.4

### ISSUE THREAD

**Issue by naresh-kumar-by** [exasol/sqlalchemy-exasol#106]
sqlalchemy_exasol python package is not compatible with new version of sqlalchemy 1.4+ when used with turbodbc dialect. Below is the code to reproduce this issue.

```python

from sqlalchemy import create_engine
 
exa_engine = create_engine("exa+turbodbc://sys:exasol@exasoldb:8888")
exa_engine.connect()
 
 
################################### ERROR #########################################
 
 
    exec(code, run_globals)
  File "/app/test.py", line 6, in <module>
    exa_engine.connect()
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 761, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect()
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 616, in __connect
    pool.dispatch.connect.for_modify(
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1676, in go
    return once_fn(*arg, **kw)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 675, in first_connect
    dialect.initialize(c)
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 394, in initialize
    self.server_version_info = self._get_server_version_info(
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy_exasol/turbodbc.py", line 82, in _get_server_version_info
    result = connection.execute(query).fetchone()[0].split('.')
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in execute
    return self._exec_driver_sql(
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1546, in _exec_driver_sql
    ret = self._execute_context(
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1696, in _execute_context
    context.pre_exec()
  File "/root/venv/lib/python3.8/site-packages/sqlalchemy_exasol/base.py", line 336, in pre_exec
    if self.isdelete or self.root_connection.dialect.server_version_info < (4, 1, 8):
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'

```

**Comment by naresh-kumar-by** [comment]
@tkilias at BlueYonder (formerly known as JDA), we are working on a fix and adding support for new sqlalchemy version, we might require additional help.

**Comment by jank** [comment]
Consider dropping support for Python 2.7 with a new release that supports SQLAlchemy 1.4. This would fix https://github.com/blue-yonder/sqlalchemy_exasol/issues/93.

**Comment by alxdb** [comment]
I'm also encountering this issue

**Comment by vasu-sharma-by** [comment]
Has there been any development on this?
I'm also facing this issue.

**Comment by Nicoretti** [comment]
Started the migration to SQLA 1.4.

* Updating the dependency itself  worked out of the box
  (no dependency conflicts)

* The plugin functionality itself is partially broken
  * **[fixed]** The issue reported by @naresh-kumar-by have been fixed
                     ("bug in pre_exec")

  * **[fixed]**       Failing tests due to usage of deprecated API

  * **[postponed]** caching was disabled, to not further complicate the migration
                         see also #190 

  * **[in progress]** Custom merge "statement" is crashing [in progress]

  * **[pending]**     Failing unit tests with new SQLA 1.4 tests suite
    - turbodbc 219 Failing  774 Test: 219 🚫, 310  🟡, 245 :heavy_check_mark: 
    - pyodbc 229 Failing  774 Test: 229 🚫, 302  🟡, 243 :heavy_check_mark: 

For more details see also PR #191

**Comment by Nicoretti** [comment]
# Status Update
After investigating various aspects of the failing custom merge statement, we concluded that a more thorough rewrite,
also considering the "new" api concept of SQLA, is the right way to address this issue.
Still beforehand we want to make sure the general functionality of the plugin is working with SQLA version 1.4.
Therefore first we will focus on addressing the more general issues caused by the SQLA upgrade.

## Status Overview

* **[in progress]** Failing Test(s)
* **[pending]** Custom merge "statement"

## Failing Test(s)

* turbodbc 219 Failing 774 Test: 218 :no_entry_sign: , 310 :yellow_circle:, 246 :heavy_check_mark:
* pyodbc 228 Failing 774 Test: 228 :no_entry_sign:, 302 :yellow_circle:, 244 :heavy_check_mark:

So far 4 major categories of failing tests have been identified:

* New tests which have been introduced in SQLA 1.4
    - New tests failing because of an not implemented functionality will be considered as new feature
      and therefore skipped and marked as missing feature for future decision (see also #143 and #198)

* Existing tests whose skip condition does to work anymore
    - Skip condition needs to be adjusted 

* Existing tests which fail since the sqla version was updated
    - This tests need to be investigated and addressed

* Others

## Attachments
* [pyodbc-tests-in-1.3-but-not-in-1.4.txt](https://github.com/exasol/sqlalchemy-exasol/files/9414647/pyodbc-tests-in-1.3-but-not-in-1.4.txt)
* [pyodbc-tests-in-1.4-but-not-in-1.3.txt](https://github.com/exasol/sqlalchemy-exasol/files/9414648/pyodbc-tests-in-1.4-but-not-in-1.3.txt)
* [turbodbc-tests-in-1.3-but-not-in-1.4.txt](https://github.com/exasol/sqlalchemy-exasol/files/9414649/turbodbc-tests-in-1.3-but-not-in-1.4.txt)
* [turbodbc-tests-in-1.4-but-not-in-1.3.txt](https://github.com/exasol/sqlalchemy-exasol/files/9414651/turbodbc-tests-in-1.4-but-not-in-1.3.txt)

**Comment by Nicoretti** [comment]
# Status Update
While fixing individual tests it became apparent that the majority of the not working tests is rather crashing than failing.
Due to the fact that a lot of the crashing tests looked like they have a similar and non api change related cause, I started investigating various of this crashes.

**What I have found so far?**
* Some test(s) which potentially would be skipped fail/crash with an error, because the general test setup crashes 
(pre skipping the test)
* Only Exasol & SQLAalchemy tests which make use of the `testing.fixtures.TablesTest` functionality for creating and cleaning up Tables + Data for testing seem to be affected 
(:warning: Not validated for all tests yet, just for the once I have investigated so far)
* Not all tables/schemas seem to be cleaned up after their associated test(s) have been run

* Common Error Messages:
  * object `OBJECT_NAME` not found
  * object `OBJECT_NAME` already exists
  * no schema specified or opened or current schema has been dropped 

**Assumptions**
* Setup/Teardown mechanic of `testing.fixtures.TablesTest` has changed
* Setup/Teardown mechanic fails due to left overs in tests DB

## Test(s) Status 
### pyodbc
63 :no_entry_sign: failed, 251 :heavy_check_mark: passed , 321 :yellow_circle:  skipped, 144 :boom: errors

### turbodbc
76 :no_entry_sign: failed, 255 :heavy_check_mark: passed , 335 :yellow_circle:  skipped, 120 :boom: errors

____________________________________________________________

**:warning: Finding and fixing the cause(s) of the crashing tests will be the main focus, before continuing with the failing tests :warning:**

**Comment by Nicoretti** [comment]
# Status Update
Further investigation's have shown that the basic SQLA test suite mostly is intact after the upgrade to `1.4` (14 failures), when run in "isolation". Various exasol specific test suites:

   * test/test_get_metadata_functions.py
   * test/test_large_metadata.py
   * test/test_regression.py (TranslateMap)

seem to have negative side effects which cause 100+ tests to  :boom: fail/crash, if run after those test suites.
This further strengthens the case for the **assumptions** mentioned in the previous update:

   * Setup/Teardown mechanic of `testing.fixtures.TablesTest` has changed
   * Setup/Teardown mechanic fails due to leftovers in tests DB

Also, this narrows down the potential root cause(s).

## Remark(s)
Common to all those test suites to be that they add/remove schemas.
For `test/test_regression.py` it have been proven that the schema manipulating test (`TranslateMap`) causes some negative side effect on following test suits.

## Notes & Ideas (from discussion with @tkilias )
* Is schema inference still working correctly?
* Does the "disabled" caching cause side effects?
* Do implicit schema open and closes affect the current schema for follow up tests?

## Next Steps
* Analyze effects of implicit open/close of schema(s)
* A more in depth analysis regarding side effects and cleanup of the mentioned test suites will be done

**Comment by Nicoretti** [comment]
# Status Update
Further analysis has shown that the majority of the crashing tests was caused,
due to implicit schema changes which have been a "side effect" of integration tests added by exasol.

In order to address this, the test setup/execution have been adjusted. 
Also further improvements regarding test robustness have been identified and are track in [#209](https://github.com/exasol/sqlalchemy-exasol/issues/209).

## Test(s) Status

### sqlalchemy
* pyodbc 13 :no_entry_sign: failed, 187 :heavy_check_mark: passed , 351 :yellow_circle:  skipped, 2 :boom: errors
* turbodbc 20 :no_entry_sign: failed, 180 :heavy_check_mark: passed , 353 :yellow_circle:  skipped, 0 :boom: errors

### exasol
* pyodbc 11 :no_entry_sign: failed, 197 :heavy_check_mark: passed , 10 :yellow_circle:  skipped, 3 :boom: errors
* turbodbc 9 :no_entry_sign: failed, 189 :heavy_check_mark: passed , 23 :yellow_circle:  skipped, 0 :boom: errors

## Next Steps
* Merge current state of patches/fixes #191 to dev branch
* Address failing tests in sqlalchemy test suite 
* Address failing tests in exasol test suite

**Comment by Nicoretti** [comment]
# Status Update

A [first set of changes](https://github.com/exasol/sqlalchemy-exasol/pull/191) which addresses various issues to support SQLA 1.4 have been merged into the the development branch (`dev-sqla-1.4`).

A first superficial analysis of the remaining failing and crashing tests has shown the following:

1.  The remaining crashing tests seem to stem from a behavioral change of sqla, so that the pyodbc based dialect now uses an additional connection for the reflection. This causes tests using the `AssertionPool` to crash.

2. There are no obvious low hanging fruit's to fix

3. A couple of the failing tests show signs that indicate, SQLA has changed how it is using/interacting with the DDL compiler of the dialect(s). Such indications are:
     * Missing/Uncreated Tables
     * Unexpected Table names

## Test(s) Status

### sqlalchemy
* pyodbc 13 :no_entry_sign: failed, 187 :heavy_check_mark: passed , 351 :yellow_circle:  skipped, 2 :boom: errors
* turbodbc 20 :no_entry_sign: failed, 180 :heavy_check_mark: passed , 353 :yellow_circle:  skipped, 0 :boom: errors

### exasol
* pyodbc 11 :no_entry_sign: failed, 197 :heavy_check_mark: passed , 10 :yellow_circle:  skipped, 3 :boom: errors
* turbodbc 9 :no_entry_sign: failed, 189 :heavy_check_mark: passed , 23 :yellow_circle:  skipped, 0 :boom: errors

## Next Steps
* Analyze if and what changed the DDL interaction/usage
    * Starting point `test.integration.sqlalchemy.test_suite.LongNameBlowoutTest_exasol`
    * Create two workspaces with sqlalchemy-exasol using SQLA 1.3 and SQLA 1.4 for comparison, to analyze behavioral change(s)
* Investigate how and why the pyodbc based dialect now creates an additional connection for reflection

**Comment by Nicoretti** [comment]
# Status Update

## Test(s) Status

### sqlalchemy
* pyodbc 10 :no_entry_sign: failed, 187 :heavy_check_mark: passed , 351 :yellow_circle:  skipped, 2 :boom: errors
* turbodbc 10 :no_entry_sign: failed, 185 :heavy_check_mark: passed , 353 :yellow_circle:  skipped, 0 :boom: errors

### exasol
* pyodbc 11 :no_entry_sign: failed, 197 :heavy_check_mark: passed , 10 :yellow_circle:  skipped, 3 :boom: errors
* turbodbc 9 :no_entry_sign: failed, 189 :heavy_check_mark: passed , 23 :yellow_circle:  skipped, 0 :boom: errors

   :spiral_notepad: nine of the failing exasol tests within `turbodbc` and `pyodbc` are caused by the custom merge statement,
   which needs to be rewritten/refactored.

**Comment by Nicoretti** [comment]
# Status Update

## Test(s) Status

### sqlalchemy
* pyodbc 3 :no_entry_sign: failed, 190 :heavy_check_mark: passed , 359 :yellow_circle:  skipped, 0 :boom: errors
    * 1 test is caused by a potentially by an escaping issue
    * 2 failing tests are caused by incorrectly returned rowcounts
* turbodbc 6 :no_entry_sign: failed, 185 :heavy_check_mark: passed , 361 :yellow_circle:  skipped, 0 :boom: errors
    * 1 test is caused by a potentially by an escaping issue
    * 5 failing tests are caused by incorrectly returned rowcounts

### exasol
* pyodbc 9 :no_entry_sign: failed, 202 :heavy_check_mark: passed , 10 :yellow_circle:  skipped, 0 :boom: errors
    * All the failing 9 tests, are caused by the custom merge statement.
* turbodbc 9 :no_entry_sign: failed, 189 :heavy_check_mark: passed , 23 :yellow_circle:  skipped, 0 :boom: errors
    * All the failing 9 tests, are caused by the custom merge statement.

## Next Steps
* Investigate the escaping issue (DifficultParametersTest_*::test_round_trip[q?marks])
* Investigate the invalid returned row counts
* Refactor/Implement Merge statement in respect to new sqla syntax/api

**Comment by Nicoretti** [comment]
# Status Update

## Test(s) Status

### sqlalchemy
* pyodbc 2 :no_entry_sign: failed, 190 :heavy_check_mark: passed , 360 :yellow_circle:  skipped, 0 :boom: errors
    * 2 failing tests are caused by incorrectly returned rowcounts
* turbodbc 5 :no_entry_sign: failed, 185 :heavy_check_mark: passed , 362 :yellow_circle:  skipped, 0 :boom: errors
    * 5 failing tests are caused by incorrectly returned rowcounts

### exasol
* pyodbc 9 :no_entry_sign: failed, 202 :heavy_check_mark: passed , 10 :yellow_circle:  skipped, 0 :boom: errors
    * All the failing 9 tests, are caused by the custom merge statement.
* turbodbc 9 :no_entry_sign: failed, 189 :heavy_check_mark: passed , 23 :yellow_circle:  skipped, 0 :boom: errors
    * All the failing 9 tests, are caused by the custom merge statement.

## Next Steps
* Investigate the invalid returned row counts
* Refactor/Implement Merge statement in respect to new sqla syntax/api

## Related Issues
* https://github.com/exasol/sqlalchemy-exasol/issues/232

**Comment by Nicoretti** [comment]
# Status Update

## Test(s) Status

### sqlalchemy
* pyodbc 0 :no_entry_sign: failed, 190 :heavy_check_mark: passed , 366 :yellow_circle:  skipped, 0 :boom: errors
* turbodbc 0 :no_entry_sign: failed, 183 :heavy_check_mark: passed , 373 :yellow_circle:  skipped, 0 :boom: errors
    * :information_source:  support is on hold

### exasol
* pyodbc 9 :no_entry_sign: failed, 202 :heavy_check_mark: passed , 10 :yellow_circle:  skipped, 0 :boom: errors
    * All the failing 9 tests, are caused by the custom merge statement.
* turbodbc 9 :no_entry_sign: failed, 189 :heavy_check_mark: passed , 23 :yellow_circle:  skipped, 0 :boom: errors
    * All the failing 9 tests, are caused by the custom merge statement.

## Next Steps
* Rework Merge statement
* Merge [dev-sqla-1.4](https://github.com/exasol/sqlalchemy-exasol/tree/dev-sqla-1.4) branch into master

## Related Issues
* https://github.com/exasol/sqlalchemy-exasol/issues/232

**Comment by Nicoretti** [comment]
# :information_source: 
```
It have been decided by PM, that the support for the custom merge statement, is dropped.
If we will be notified, that someone depends on this feature, we are open to add it again.
```

**Comment by jcharlytown** [comment]
Hi @Nicoretti , we are using sqlalchemy-exasol at my current company. We still need to evaluate if we're using custom merge statements within our code base. What's the ETA for giving feedback on this?

Also, one more question: I see that the 1.4 branch drops support for <1.4. Will a version which supports <1.4 continue to be maintained, or will this project stop supporting <1.4 altogether once this effort completes?

Thanks!

**Comment by Nicoretti** [comment]
Hi @jcharlytown,

> We still need to evaluate if we're using custom merge statements within our code base. What's the ETA for giving feedback on this?

Take your time, the changes will be published as `major` release, if your dependency is pinned to stay on a specific
major version you will be good.
* [poetry-dependency-specification](https://python-poetry.org/docs/dependency-specification/)
* [setuptools-dependency-specification](https://setuptools.pypa.io/en/latest/pkg_resources.html#requirement-objects)

:spiral_notepad: Side note: If the `Merge` statement is added again it's very likely that we need to change the API (usage/syntaxt) of it. 

Regarding your second question

> Also, one more question: I see that the 1.4 branch drops support for <1.4. Will a version which supports <1.4 continue to be maintained, or will this project stop supporting <1.4 altogether once this effort completes?

In order to answer this in more detail, I will need to consult our project management about it.
(I'll try to come back to you with an answer, as soon as possible)

best
Nico

**Comment by Nicoretti** [comment]
Hi @jcharlytown, 

I had a brief discussion with our project management, and we concluded not to maintain two lines.

**Why is that?**
---
* If something unforeseen and critical regarding the version(s) supporting SQLA 1.3 would surface, we still would be able to address this if needed.
    :information_source: That said, we still advice to update to a version supporting `SQLA 1.4` in the near future.   :information_source: 

* [SQLA 1.3](https://docs.sqlalchemy.org/en/13/) is a legacy version
 `Release: 1.3.24 legacy version | Release Date: March 30, 2021`
  
* [sqlalchemy-exasol 2.2.0](https://pypi.org/project/sqlalchemy-exasol/2.2.0/) have been around for more than 2 years and we only had one external bug report in the last year.

* [sqlalchemy-exasol 2.2.0 - 3.2.2](https://pypi.org/project/sqlalchemy-exasol/#history) (all supporting SQLA 1.3) still can be used

best
Nico

See also https://github.com/exasol/sqlalchemy-exasol/discussions/250
