### ISSUE TITLE
Remove workaround for missing prepared delete support in EXASOL

### ISSUE THREAD

**Issue by jank** [exasol/sqlalchemy-exasol#5]
Once supported by EXASOL, the workaround in base.py for prepared delete must be removed.

Depends on 
[open] https://www.exasol.com/support/browse/EXASOL-899
[resolved in 4.2] https://www.exasol.com/support/browse/EXASOL-875

**Comment by vamega** [comment]
I don't think this will work correctly with `turbodbc`.
When I remove the `self.isdelete` from the `pre_exec` method in `base.py`, I get a `MemoryError: bad allocation`. I'll try to do some more digging and see if I can make a reproducible test case.

The current spot where I see this has a very large number of parameters.

**Comment by vamega** [comment]
Actually, I think this cannot be removed yet.
Reducing the number of parameters caused me to bump into this error:

```
Feature not supported: Prepared DELETE with parameterized condition other than <column name> = ? or unsupported type
```

My condition was to delete using an `IN` clause.

Using the current logic for statement construction, it appears that there is excessive allocation happening in the `pre_exec`, since it performs repeated string replacement.

I will provide a PR that changes this to use a template based single replacement, since that should dramatically increase performance when there are a large number of parameters.

**Comment by jank** [comment]
@vamega reading the EXASOL ticket https://www.exasol.com/support/browse/EXASOL-875

> Currently, a DELETE statement may only have one prepared parameter.
> We will allow multiple parameters, but only if they are no expressions and combined via AND, e.g. "col1=? AND col2=?".

only a special case for parameterized DELETE was implemented.

**Comment by ravinirmal10** [comment]
I am using JDBC driver to connect to Exasol DB and I am seeing similar issue, I am using delete query with only one prepared parameter in `WHERE` condition. 
```
java.sql.SQLException: Feature not supported: Prepared DELETE with parameterized condition other than <column name> = ? or unsupported type
```
As per the Exasol ticket https://www.exasol.com/support/browse/EXASOL-875, I assume that they have added support to allow multiple prepared parameter for `DELETE` but I am not understanding why single prepared parameter support is removed.
