### ISSUE TITLE
Release a 2.1.0 version removing Travis CI and using odbc metadata

### ISSUE THREAD

**Issue by fergarzag91** [exasol/sqlalchemy-exasol#95]
I'm currently working on a new release to remove Travis CI completely and replace it with Github Actions. Additionally, this version will contain the new ODBC medatata requested by @tkilias in #90

**Comment by tkilias** [comment]
@nndo1991 Let me know if you need help.

**Comment by jank** [comment]
@nndo1991 - thank you for picking up this issue. For the release, please include the following changes also to documentation

- [ ] The https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/README.rst is updated, the Travis badge is replaced with a GH action badge
- [ ] The https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/INTEGRATION_TEST.md is updated so that all references to Travis are removed, instead have a short intro on how to run the GH Actions tests and where to find the repo with the EXASOL test images
- [ ] Remove the upload of test coverage to coveralls from the build file, remove the badge from the README.rst, create an issue so that we do not forget to re-add this in future
